/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as BasicGcdRouteImport } from './routes/basic/gcd'
import { Route as CiphersAdditiveRouteImport } from './routes/ciphers/additive'
import { Route as CiphersAffineRouteImport } from './routes/ciphers/affine'
import { Route as CiphersMultiplicativeRouteImport } from './routes/ciphers/multiplicative'
import { Route as DiophantineLinearRouteImport } from './routes/diophantine/linear'
import { Route as DiophantineSimultaneousRouteImport } from './routes/diophantine/simultaneous'
import { Route as DiophantineSingleVarRouteImport } from './routes/diophantine/single-var'
import { Route as ModularAdditiveInverseRouteImport } from './routes/modular/additive-inverse'
import { Route as ModularMatrixInverseRouteImport } from './routes/modular/matrix-inverse'
import { Route as ModularMultiplicativeInverseRouteImport } from './routes/modular/multiplicative-inverse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicGcdRoute = BasicGcdRouteImport.update({
  id: '/basic/gcd',
  path: '/basic/gcd',
  getParentRoute: () => rootRouteImport,
} as any)
const CiphersAdditiveRoute = CiphersAdditiveRouteImport.update({
  id: '/ciphers/additive',
  path: '/ciphers/additive',
  getParentRoute: () => rootRouteImport,
} as any)
const CiphersAffineRoute = CiphersAffineRouteImport.update({
  id: '/ciphers/affine',
  path: '/ciphers/affine',
  getParentRoute: () => rootRouteImport,
} as any)
const CiphersMultiplicativeRoute = CiphersMultiplicativeRouteImport.update({
  id: '/ciphers/multiplicative',
  path: '/ciphers/multiplicative',
  getParentRoute: () => rootRouteImport,
} as any)
const DiophantineLinearRoute = DiophantineLinearRouteImport.update({
  id: '/diophantine/linear',
  path: '/diophantine/linear',
  getParentRoute: () => rootRouteImport,
} as any)
const DiophantineSimultaneousRoute = DiophantineSimultaneousRouteImport.update({
  id: '/diophantine/simultaneous',
  path: '/diophantine/simultaneous',
  getParentRoute: () => rootRouteImport,
} as any)
const DiophantineSingleVarRoute = DiophantineSingleVarRouteImport.update({
  id: '/diophantine/single-var',
  path: '/diophantine/single-var',
  getParentRoute: () => rootRouteImport,
} as any)
const ModularAdditiveInverseRoute = ModularAdditiveInverseRouteImport.update({
  id: '/modular/additive-inverse',
  path: '/modular/additive-inverse',
  getParentRoute: () => rootRouteImport,
} as any)
const ModularMatrixInverseRoute = ModularMatrixInverseRouteImport.update({
  id: '/modular/matrix-inverse',
  path: '/modular/matrix-inverse',
  getParentRoute: () => rootRouteImport,
} as any)
const ModularMultiplicativeInverseRoute =
  ModularMultiplicativeInverseRouteImport.update({
    id: '/modular/multiplicative-inverse',
    path: '/modular/multiplicative-inverse',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/basic/gcd': typeof BasicGcdRoute
  '/ciphers/additive': typeof CiphersAdditiveRoute
  '/ciphers/affine': typeof CiphersAffineRoute
  '/ciphers/multiplicative': typeof CiphersMultiplicativeRoute
  '/diophantine/linear': typeof DiophantineLinearRoute
  '/diophantine/simultaneous': typeof DiophantineSimultaneousRoute
  '/diophantine/single-var': typeof DiophantineSingleVarRoute
  '/modular/additive-inverse': typeof ModularAdditiveInverseRoute
  '/modular/matrix-inverse': typeof ModularMatrixInverseRoute
  '/modular/multiplicative-inverse': typeof ModularMultiplicativeInverseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/basic/gcd': typeof BasicGcdRoute
  '/ciphers/additive': typeof CiphersAdditiveRoute
  '/ciphers/affine': typeof CiphersAffineRoute
  '/ciphers/multiplicative': typeof CiphersMultiplicativeRoute
  '/diophantine/linear': typeof DiophantineLinearRoute
  '/diophantine/simultaneous': typeof DiophantineSimultaneousRoute
  '/diophantine/single-var': typeof DiophantineSingleVarRoute
  '/modular/additive-inverse': typeof ModularAdditiveInverseRoute
  '/modular/matrix-inverse': typeof ModularMatrixInverseRoute
  '/modular/multiplicative-inverse': typeof ModularMultiplicativeInverseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/settings': typeof SettingsRoute
  '/basic/gcd': typeof BasicGcdRoute
  '/ciphers/additive': typeof CiphersAdditiveRoute
  '/ciphers/affine': typeof CiphersAffineRoute
  '/ciphers/multiplicative': typeof CiphersMultiplicativeRoute
  '/diophantine/linear': typeof DiophantineLinearRoute
  '/diophantine/simultaneous': typeof DiophantineSimultaneousRoute
  '/diophantine/single-var': typeof DiophantineSingleVarRoute
  '/modular/additive-inverse': typeof ModularAdditiveInverseRoute
  '/modular/matrix-inverse': typeof ModularMatrixInverseRoute
  '/modular/multiplicative-inverse': typeof ModularMultiplicativeInverseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/settings'
    | '/basic/gcd'
    | '/ciphers/additive'
    | '/ciphers/affine'
    | '/ciphers/multiplicative'
    | '/diophantine/linear'
    | '/diophantine/simultaneous'
    | '/diophantine/single-var'
    | '/modular/additive-inverse'
    | '/modular/matrix-inverse'
    | '/modular/multiplicative-inverse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/settings'
    | '/basic/gcd'
    | '/ciphers/additive'
    | '/ciphers/affine'
    | '/ciphers/multiplicative'
    | '/diophantine/linear'
    | '/diophantine/simultaneous'
    | '/diophantine/single-var'
    | '/modular/additive-inverse'
    | '/modular/matrix-inverse'
    | '/modular/multiplicative-inverse'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/settings'
    | '/basic/gcd'
    | '/ciphers/additive'
    | '/ciphers/affine'
    | '/ciphers/multiplicative'
    | '/diophantine/linear'
    | '/diophantine/simultaneous'
    | '/diophantine/single-var'
    | '/modular/additive-inverse'
    | '/modular/matrix-inverse'
    | '/modular/multiplicative-inverse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SettingsRoute: typeof SettingsRoute
  BasicGcdRoute: typeof BasicGcdRoute
  CiphersAdditiveRoute: typeof CiphersAdditiveRoute
  CiphersAffineRoute: typeof CiphersAffineRoute
  CiphersMultiplicativeRoute: typeof CiphersMultiplicativeRoute
  DiophantineLinearRoute: typeof DiophantineLinearRoute
  DiophantineSimultaneousRoute: typeof DiophantineSimultaneousRoute
  DiophantineSingleVarRoute: typeof DiophantineSingleVarRoute
  ModularAdditiveInverseRoute: typeof ModularAdditiveInverseRoute
  ModularMatrixInverseRoute: typeof ModularMatrixInverseRoute
  ModularMultiplicativeInverseRoute: typeof ModularMultiplicativeInverseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic/gcd': {
      id: '/basic/gcd'
      path: '/basic/gcd'
      fullPath: '/basic/gcd'
      preLoaderRoute: typeof BasicGcdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ciphers/additive': {
      id: '/ciphers/additive'
      path: '/ciphers/additive'
      fullPath: '/ciphers/additive'
      preLoaderRoute: typeof CiphersAdditiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ciphers/affine': {
      id: '/ciphers/affine'
      path: '/ciphers/affine'
      fullPath: '/ciphers/affine'
      preLoaderRoute: typeof CiphersAffineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ciphers/multiplicative': {
      id: '/ciphers/multiplicative'
      path: '/ciphers/multiplicative'
      fullPath: '/ciphers/multiplicative'
      preLoaderRoute: typeof CiphersMultiplicativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diophantine/linear': {
      id: '/diophantine/linear'
      path: '/diophantine/linear'
      fullPath: '/diophantine/linear'
      preLoaderRoute: typeof DiophantineLinearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diophantine/simultaneous': {
      id: '/diophantine/simultaneous'
      path: '/diophantine/simultaneous'
      fullPath: '/diophantine/simultaneous'
      preLoaderRoute: typeof DiophantineSimultaneousRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diophantine/single-var': {
      id: '/diophantine/single-var'
      path: '/diophantine/single-var'
      fullPath: '/diophantine/single-var'
      preLoaderRoute: typeof DiophantineSingleVarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modular/additive-inverse': {
      id: '/modular/additive-inverse'
      path: '/modular/additive-inverse'
      fullPath: '/modular/additive-inverse'
      preLoaderRoute: typeof ModularAdditiveInverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modular/matrix-inverse': {
      id: '/modular/matrix-inverse'
      path: '/modular/matrix-inverse'
      fullPath: '/modular/matrix-inverse'
      preLoaderRoute: typeof ModularMatrixInverseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modular/multiplicative-inverse': {
      id: '/modular/multiplicative-inverse'
      path: '/modular/multiplicative-inverse'
      fullPath: '/modular/multiplicative-inverse'
      preLoaderRoute: typeof ModularMultiplicativeInverseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SettingsRoute: SettingsRoute,
  BasicGcdRoute: BasicGcdRoute,
  CiphersAdditiveRoute: CiphersAdditiveRoute,
  CiphersAffineRoute: CiphersAffineRoute,
  CiphersMultiplicativeRoute: CiphersMultiplicativeRoute,
  DiophantineLinearRoute: DiophantineLinearRoute,
  DiophantineSimultaneousRoute: DiophantineSimultaneousRoute,
  DiophantineSingleVarRoute: DiophantineSingleVarRoute,
  ModularAdditiveInverseRoute: ModularAdditiveInverseRoute,
  ModularMatrixInverseRoute: ModularMatrixInverseRoute,
  ModularMultiplicativeInverseRoute: ModularMultiplicativeInverseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
