/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MarketsRouteImport } from './routes/markets'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as BasicGcdRouteImport } from './routes/basic/gcd'
import { Route as DiophantineLinearRouteImport } from './routes/diophantine/linear'
import { Route as ModularAdditiveInverseRouteImport } from './routes/modular/additive-inverse'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketsRoute = MarketsRouteImport.update({
  id: '/markets',
  path: '/markets',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const BasicGcdRoute = BasicGcdRouteImport.update({
  id: '/basic/gcd',
  path: '/basic/gcd',
  getParentRoute: () => rootRouteImport,
} as any)
const DiophantineLinearRoute = DiophantineLinearRouteImport.update({
  id: '/diophantine/linear',
  path: '/diophantine/linear',
  getParentRoute: () => rootRouteImport,
} as any)
const ModularAdditiveInverseRoute = ModularAdditiveInverseRouteImport.update({
  id: '/modular/additive-inverse',
  path: '/modular/additive-inverse',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/basic/gcd': typeof BasicGcdRoute
  '/diophantine/linear': typeof DiophantineLinearRoute
  '/modular/additive-inverse': typeof ModularAdditiveInverseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/basic/gcd': typeof BasicGcdRoute
  '/diophantine/linear': typeof DiophantineLinearRoute
  '/modular/additive-inverse': typeof ModularAdditiveInverseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/markets': typeof MarketsRoute
  '/settings': typeof SettingsRoute
  '/watchlist': typeof WatchlistRoute
  '/basic/gcd': typeof BasicGcdRoute
  '/diophantine/linear': typeof DiophantineLinearRoute
  '/modular/additive-inverse': typeof ModularAdditiveInverseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/markets'
    | '/settings'
    | '/watchlist'
    | '/basic/gcd'
    | '/diophantine/linear'
    | '/modular/additive-inverse'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/markets'
    | '/settings'
    | '/watchlist'
    | '/basic/gcd'
    | '/diophantine/linear'
    | '/modular/additive-inverse'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/markets'
    | '/settings'
    | '/watchlist'
    | '/basic/gcd'
    | '/diophantine/linear'
    | '/modular/additive-inverse'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  MarketsRoute: typeof MarketsRoute
  SettingsRoute: typeof SettingsRoute
  WatchlistRoute: typeof WatchlistRoute
  BasicGcdRoute: typeof BasicGcdRoute
  DiophantineLinearRoute: typeof DiophantineLinearRoute
  ModularAdditiveInverseRoute: typeof ModularAdditiveInverseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/markets': {
      id: '/markets'
      path: '/markets'
      fullPath: '/markets'
      preLoaderRoute: typeof MarketsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/basic/gcd': {
      id: '/basic/gcd'
      path: '/basic/gcd'
      fullPath: '/basic/gcd'
      preLoaderRoute: typeof BasicGcdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diophantine/linear': {
      id: '/diophantine/linear'
      path: '/diophantine/linear'
      fullPath: '/diophantine/linear'
      preLoaderRoute: typeof DiophantineLinearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modular/additive-inverse': {
      id: '/modular/additive-inverse'
      path: '/modular/additive-inverse'
      fullPath: '/modular/additive-inverse'
      preLoaderRoute: typeof ModularAdditiveInverseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  MarketsRoute: MarketsRoute,
  SettingsRoute: SettingsRoute,
  WatchlistRoute: WatchlistRoute,
  BasicGcdRoute: BasicGcdRoute,
  DiophantineLinearRoute: DiophantineLinearRoute,
  ModularAdditiveInverseRoute: ModularAdditiveInverseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
